name = "cf_ai_chatbot"
main = "src/index.js"
compatibility_date = "2025-10-16"
format = "modules" # This line fixes the build error

# Binding for Workers AI
[ai]
binding = "AI"

[build]
external = ["@cloudflare/ai"]

[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = "2f813e2b0fea45ceabe5f812ea5f4b94"
